# ===============================
# Site settings
# ===============================

lang: en
timezone: Asia/Kathmandu

title: ""
tagline: ""
description: >-
  Cybersecurity write-ups, CTFs, penetration testing,
  security research, projects and notes.

url: "https://sagar-bhattarai.github.io"
baseurl: ""

github:
  username: sagar-bhattarai

social:
  name: "Sagar Bhattarai"
  email: ""
  links:
    - https://github.com/sagar-bhattarai
    - https://www.linkedin.com/in/yourusername/
    - https://twitter.com/yourusername
    - https://www.instagram.com/yourusername/

theme: jekyll-theme-chirpy

# ===============================
# Jekyll
# ===============================

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

collections:
  tabs:
    output: true
    sort_by: order
    collections:

  levels:
    output: true
    permalink: /levels-:name/

  platforms:
    output: true
    permalink: /platforms-:name/

  series:
    output: true
    permalink: /series-:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page

# ===============================
# Archives
# ===============================

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# ===============================
# Chirpy
# ===============================

toc: true

paginate: 10
paginate_path: /page/:num/

theme_mode:

avatar: /assets/images/profile.jpeg

social_preview_image:

comments:
  active: false

pwa:
  enabled: true

analytics:
  provider:
  google:
    id:

pageviews:
  provider:
  google:
    property:

assets:
  self_host:
    enabled: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
